In [0]:
from keras.models import Sequential
from keras.layers import Dense
import numpy as np

In [0]:
weight1=np.array([[0.2,-0.3],[0.4,0.1],[-0.5,0.2]])
bias1=np.array([0.4,0.2])
weight2=np.array([[-0.3,0.2,0.6],[-0.2,-0.1,-0.2]])
bias2=np.array([0.1,0.1,0.2])
weight3=np.array([[0.3,0.2],[-0.5,0.5],[0.7,0.2]])
bias3=np.array([-0.1,-0.2])
weights=[weight1,bias1,weight2,bias2,weight3,bias3]

In [0]:
model = Sequential()
hidden1 = model.add(Dense(2,activation="sigmoid",input_dim=3))
hidden2=model.add(Dense(3,activation="sigmoid"))
o = model.add(Dense(2,activation="sigmoid"))
model.compile(loss="mean_squared_error",optimizer="Adam",metrics=['accuracy'])
model.set_weights(weights)

In [0]:
x=np.array([[1,0,1]])
y=np.array([[1,0]])
model.fit(x,y,epochs=1)

Epoch 1/1
1/1 [==============================] - 0s 303ms/step - loss: 0.2648 - acc: 0.0000e+00


In [0]:
score = model.evaluate(x,y, verbose=0)
print('Test loss:', score[0])
print('Test accuracy:', score[1])

Test loss: 0.264284610748291
Test accuracy: 0.0


In [0]:
model.get_weights()

[array([[ 0.20072854, -0.2992777 ],
        [ 0.4       ,  0.1       ],
        [-0.49927148,  0.20072232]], dtype=float32),
 array([0.40072852, 0.20072232], dtype=float32),
 array([[-0.299259  ,  0.19925602,  0.6007438 ],
        [-0.19925901, -0.10074399, -0.19925624]], dtype=float32),
 array([0.10074248, 0.09925594, 0.20074394], dtype=float32),
 array([[ 0.3007441,  0.1992559],
        [-0.4992559,  0.4992559],
        [ 0.7007441,  0.1992559]], dtype=float32),
 array([-0.09925589, -0.20074412], dtype=float32)]

In [0]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_16 (Dense)             (None, 2)                 8         
_________________________________________________________________
dense_17 (Dense)             (None, 3)                 9         
_________________________________________________________________
dense_18 (Dense)             (None, 2)                 8         
Total params: 25
Trainable params: 25
Non-trainable params: 0
_________________________________________________________________
